mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('theStash.urls')),
    path('stashEditor/', include('stashEditor.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('stashProfile/', include('stashProfile.urls')),
]


#might uncomment for image upload

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/stashEditor/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views


app_name = 'stashEditor'
urlpatterns = [
    path('create', views.create, name='create'),
    path('how_it_works', views.how_it_works, name='how_it_works'),
    #Request från create.html för att lägga till kategorier i en lista och/eller spara nya kategorier till db.
    url(r'^ajax/validate_categories/$',
        views.validate_categories, name='validate_categories'),
]

mysite/theStash/urls.py
from django.urls import path

from . import views
from django.conf.urls import url 

app_name = 'theStash'
urlpatterns = [
    path('', views.index, name='theStashindex'),
    path('theStash/signup', views.signup, name='signup'),
    path('theStash/search_result/', views.search_result, name='search_result'),
    path('<int:user_id>/<int:idea_id>/', views.detail, name='detail'),
    path('theStash/<str:category_name>/',
         views.category_detail, name='category_detail'),
    path('most_liked', views.most_liked, name='most_liked'),
    url(r'^ajax/like_counter/$', views.like_counter, name='like_counter'),
    url(r'^ajax/like_comment/$', views.like_comment, name='like_comment'),

]

mysite/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

    <head>
        {% block title %}<title>CreativeStash</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Import bootstrap CSS-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

        <!-- Add additional CSS in static file -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/globalstyle.css' %}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Odibee+Sans&display=swap" rel="stylesheet">
        



    </head>


    <!-- Skriv url-namn som appnamn:viewnamn
    tex: href="{% url 'theStash:theStashindex' %}"

    (städa bort denna kommentar)-->

    <body>
        <nav class="navbar navbar-expand-lg p-3 mb-2 navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'theStash:theStashindex' %}">CREATIVE STASH</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'stashEditor:create' %}">Create Idea</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'theStash:most_liked' %}">Most liked</a>
                        </li>
                  
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'stashEditor:how_it_works'%}">How it works</a>
                      </li>
                    </ul>


                

                    <form class="d-flex" action="{% url 'theStash:search_result' %}" method="get">
                        <div class="input-group">
                            <input class="form-control" type="search" placeholder="Type here to search"
                                aria-label="Search" id="searchbox" name="q">
                            <button type="submit" class="btn btn-outline-warning">Search</button>
                        </div>

                    </form>


                    <div class="dropdown">

                        {% if user.is_authenticated %}
                        <button class="btn btn-outline-warning dropdown-toggle" type="button" id="navbar-account-button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.get_username }}
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbar-account-button">
                            <li><a class="dropdown-item" href="/stashProfile/social_profile/{{ user.id }}">Profile</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'logout'%}">Logout</a></li>
                        </ul>
                        {% else %}
                        <button class="btn btn-warning dropdown-toggle" type="button" id="navbar-account-button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Login/Sign Up
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="navbar-account-button">
                            <li><a class="dropdown-item" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                            <li><a class="dropdown-item" href="{% url 'theStash:signup'%}">Signup</a></li>
                        </ul>
                        {% endif %}
                    </div>
                </div>

            </div>
        </nav>
        <main class="container-fluid ">
            
            <div class="row justify-content-md-center main-body">
                <div class="col-sm-10">

                    {% block content %}




                    <!-- This is where extensions of this html document appear-->




                    {% endblock %}
                  
                </div>
            </div>
        </main>
    
            <a id="topbutton" href="#">BACK TO TOP &#8593;</a>
            
        <footer>
            <div class="container">
                <div class="row text-center">
                    <div class="col-md-4">
                        <h5 class=text-warning>Creative Stash</h5>
                        <p> This is a project by Group 14 in course DA336A-TS043, Spring 2021.
                            Bachelor of Science in Computer and Information Science, Malmö University.
                        </p>

                    </div>
                    <div class="col-md-4">
                        <h5 class=text-warning>Quick links</h5>
                        <ul class="list-unstyled quick-links">
                            <li><a href="/"><i class="fa fa-angle-double-right"></i>Home</a></li>
                            <li><a href="{% url 'stashEditor:how_it_works'%}"><i
                                        class="fa fa-angle-double-right"></i>Get Started</a></li>
                        </ul>
                    </div>

                    <div class="col-md-4">
                        <h5 class=text-warning>Location</h5>
                        <p>Nordenskiöldsgatan 1, 211 19 Malmö</p>
                        <p> 040-665 70 00</p>
                        
                    </div>

                    

                </div>
            </div>

        </footer>

        
        

        <!-- Import Bootstrp JavaScript START -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
            integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
            integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
            crossorigin="anonymous"></script>
        <!-- Import Bootstrp JavaScript ENDS -->
        <!-- Import Jquery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="{% static 'js/globalscripts.js' %}"></script>

        {% block javascript %}
        <!-- Dessa tags fungerar på samma sätt som block content och endblock fast med scripts. Lägg dessa block på en html sida, skriv js och det kommer hamna här.-->
        {% endblock %}


    </body>

</html>