mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('theStash.urls')),
    path('stashEditor/', include('stashEditor.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('stashProfile/', include('stashProfile.urls')),
]


#might uncomment for image upload

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/stashEditor/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views


app_name = 'stashEditor'
urlpatterns = [
    path('create', views.create, name='create'),
    path('how_it_works', views.how_it_works, name='how_it_works'),
    #Request från create.html för att lägga till kategorier i en lista och/eller spara nya kategorier till db.
    url(r'^ajax/validate_categories/$',
        views.validate_categories, name='validate_categories'),
]

mysite/theStash/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields import IntegerField


# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=100, primary_key=True)

    def __str__(self):
        return self.category_name

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_profile")
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(upload_to='./profilepics/', null=True, blank=True)
    #optional social links connected to user profile
    vimeo = models.URLField(max_length=200, blank=True)
    behance = models.URLField(max_length=200, blank=True)
    instagram = models.URLField(max_length=200, blank=True)
    user_interests = models.ManyToManyField(Category, blank=True)

    def __str__(self):
        return self.bio



class Idea(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="creator")
    idea_title = models.CharField(max_length=30)
    idea_description = models.TextField(blank=True)
    #an idea can be turned public but is private by default
    idea_category = models.ManyToManyField(Category, related_name="list_idea_categories")
    is_public = models.BooleanField(default=False)
    image = models.ImageField(upload_to='./media/', null=True, blank=True)
    created_date = models.DateField(auto_now_add=True)
    updated_when = models.DateField(auto_now=True)

    def __str__(self):
        return self.idea_title
    
class Comments(models.Model):
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE, related_name="comments_idea")
    idea_comment = models.TextField()
    comment_likes = IntegerField(null= True) 
    from_user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.idea_comment

class Like(models.Model):
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE, related_name="likes") 
    idea_like = models.IntegerField(null=True) 


    def __str__(self):
        self.namn="test"
        return self.namn  

mysite/stashEditor/forms.py
from django import forms
from theStash.models import Idea, Category


class CreateIdeaForm(forms.ModelForm):

    class Meta:
        model = Idea
        fields = ['idea_title', 'idea_description', 'is_public', 'image']


class CreateCategoryFrom(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['category_name']

mysite/stashEditor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from theStash.models import Idea, Category
from .forms import CreateIdeaForm, CreateCategoryFrom


list_of_categories = []

def validate_categories(request):
    category_name = request.GET.get('category_name', None)
    data = {
        'is_taken': Category.objects.filter(category_name__iexact=category_name).exists()
    }

    global list_of_categories
    list_of_categories.append(category_name)

    if data['is_taken']:
        data['category'] = category_name
    else:
        data['category'] = category_name
        new_category = Category(category_name=category_name)
        new_category.save()

    return JsonResponse(data)



@login_required
def create(request):
    template = loader.get_template('stashEditor/create.html')
    fs = FileSystemStorage()

    if request.method == 'POST':
        global list_of_categories
        create_idea_form = CreateIdeaForm(request.POST)

        # check if form data is valid
        if create_idea_form.is_valid():
            uploaded_picture = request.FILES.get('image')
            # Return an object without saving to the DB
            form_object = create_idea_form.save(commit=False)

            # Add an author field which will contain current user's id
            form_object.creator = User.objects.get(pk=request.user.id)


            if uploaded_picture:
                #Save the uploaded image
                name = fs.save(f"upload-{uploaded_picture.name}", uploaded_picture)
                url = fs.url(name)
                form_object.image = url

            else:
                form_object.image = '/media/default_idea.jpg'

            # Save the final "real form" to the DB
            form_object.save()

            for item in list_of_categories:
                form_object.idea_category.add(item)

            list_of_categories = []

            return redirect(f'/{form_object.creator.id}/{form_object.id}')



    else:

        create_idea_form = CreateIdeaForm()

        context = {
            'ideaform': create_idea_form
            }

        return HttpResponse(template.render(context, request))


def how_it_works(request):
    template = loader.get_template('stashEditor/how_it_works.html')
    context = {
        }
    return HttpResponse(template.render(context, request))

mysite/stashEditor/templates/stashEditor/create.html
{% extends "base_generic.html" %}



{% block javascript %}
<script>
    
    $("#submit_idea_form").click(function () {
        var empt = document.forms["create"]["idea_title"].value;
        if (empt == "") {
            $("#id_idea_title").css("background-color", "#fa9f91");
            return false;
        } else if (document.forms["create"]["idea_description"].value == "") {
            $("#id_idea_description").css("background-color", "#fa9f91");
            return false;

        } else {
            $("#progress-bar-create").css("display", "flex");
            $("#progression-width").css("width", "100%");
            setTimeout(
                function () {
                    $("#idea_form").submit();
                }, 1000);
        }

    });

    $("#id_category_name").change(function () {
        var category_name = $(this).val();

        $.ajax({
            url: '/stashEditor/ajax/validate_categories/',
            data: {
                'category_name': category_name
            },
            dataType: 'json',
            success: function (data) {
                $("#categories").append(data.category + ', ');
                $("#id_category_name").val("");
            }
        });
    });

    $(document).ready(function () {
        $('#id_is_public').click(function () {
            if ($(this).prop("checked") == true) {
                $("#submit_idea_form").text("Publish");
            }
            else if ($(this).prop("checked") == false) {
                $("#submit_idea_form").text("Save");
            }
        });
    });


</script>

{% endblock %}


{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/stashEditor/style.css' %}">


<div class="container d-flex justify-content-center" id="create-page">
    <div class="col-sm-8 mt-5">
        <h2 class="bg-warning text-dark rounded text-center">Publish new idea</h2>
        {% load crispy_forms_tags %}
        <form name="create" action="" method="post" id="idea_form" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="sm-5">
                {{ideaform.idea_title|as_crispy_field}}
                <small class="form-text text-muted">Choose a suitable title for your project</small>

                {{ideaform.idea_description|as_crispy_field}}
                <small class="form-text text-muted">Describe your project</small><br>
            </div>

            <div class="sm-5">
                <label for="id_category_name" class="form-label " id="div_id_add_category">Add categories to your
                    idea</label>
                <input type="text" class="form-control" id="id_category_name"
                    placeholder="e.g. cloud computing or cryptocurrency" required>
                <small class="form-text text-muted">Categories help people find your public ideas on
                    CreativeStash</small>

                <strong id="categories"></strong><br>

                <label class="form-label" for="imageupload" id="div_id_add_image">Upload image</label>
                <input class="form-control" type="file" name="image" id="imageupload">

                {{ideaform.is_public|as_crispy_field}}
            </div>
        </form>


        <div class="sm-5 d-flex justify-content-center" id="form_submit_button_box">
            <button class="btn btn-warning w-25" id="submit_idea_form">Save</button>
            <div class="w-25"></div>
            <a href="/" class="btn btn-danger profile-button w-25">Cancel</a>

        </div>
        <div class="progress mt-4" id="progress-bar-create" style="height: 20px;">
            <div class="progress-bar progress-bar-striped bg-info progress-bar-animated" id="progression-width"
                role="progressbar" style="width: 0%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">Publishing
            </div>
        </div>

    </div>

</div>
</div>
{% endblock %}

mysite/stashEditor/templates/stashEditor/how_it_works.html
{% extends "base_generic.html" %}


{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/stashEditor/style.css' %}">


<h1> What counts as an idea?</h1>
    <p> An idea refers to a, usually, spontaneous thought over a certain area or
        for a certain reasoning.
    </p>
    <p>What characterizes an idea is that it focuses on the <b>new or original.</b></p>
    <p>In Creative Stash, we welcome ideas that revolve around the arts, from digital to traditional.</p>

<h1>How it works</h1>
    <h2> 1. Idea</h2>
        <p> Pick out your best idea with a suitable title and description.</p>

    <h2>2. Picture</h2>
        <p>Choose <b>ONE</b> image that best describes your idea. If you don't have one yet, Creative Stash will give you one.</p>

    <h2>3. Save</h2>
        <p>Save your idea privately or publish it!</p>

  <h2>About Categories</h2>
  <p>Help people find your idea by associating it to meaningful keywords.
    Other creators on CreativeStash will always be able to search for public ideas by title or author,
    but you can help them find what they like by tagging your creations meaningfully.</p>

  <h2>Inspiration</h2>
  <p>On Creative Stash you can search for any word and discover many inspiring examples of ideas.</p>


<h1>Ready? Let's get started!</h1>
    <p> Once you have created a profile you can start publishing your ideas,
      or just writing them down for later.     Just follow: 
        <a href="{% url 'stashEditor:create' %}">Create your first idea</a>
    </p>




{% endblock %}